[package]
name = "hermit-rs-template"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "0.3"
tiny_http = "0.12"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = "0.9"

[features]
default = ["hermit/acpi", "hermit/pci", "hermit/pci-ids", "hermit/tcp","hermit/shell"]
ci = []
